### ISSUE TITLE
Chronograf is running on port 8888 and not 3004

### ISSUE THREAD

**Issue by nikhilno1** [artlov/docker-telegraf-influxdb-grafana#3] opened 2020-05-27 11:15 UTC
Thank you for this repo. I was able to get it working in no time.
Just a couple of issues, Chronograf is running on port 8888 and not 3004.
Also the first time I had a problem where influxd was continuously crashing. Below command from inside the container fixed it:
`chown -R influxdb:influxdb /var/lib/influxdb `
The permissions for this folder were set incorrectly.

**Comment by artlov** [comment] 2020-06-04 18:08
Chonograf port mapping fixed in [19f1fd0](https://github.com/artlov/docker-telegraf-influxdb-grafana/commit/19f1fd0bfbb7329ba567b155e3e0b993d8b1d1df).
I can't reproduce influxdb permissions issue. Do you use volume mapping? In that case it may be necessary to set permissions separatly, exactly as you did.

**Closed as completed** 2020-06-04 20:07 UTC
